### ISSUE TITLE
Possible glitch in project operator.

### ISSUE THREAD

**Issue by PaulKlint** [usethesource/vallang#4]
```
rascal>("a" : 1, "b" : 2, "c" : 3)<1,0,1>;
java.lang.IllegalStateException: Binary relation patterns exhausted.(internal error)    at $shell$(|main://$shell$|)
java.lang.IllegalStateException: Binary relation patterns exhausted.
        at io.usethesource.vallang.impl.persistent.PersistentHashIndexedBinaryRelation$1.project(PersistentHashIndexedBinaryRelation.java:587)
        at io.usethesource.vallang.impl.persistent.PersistentHashIndexedBinaryRelation$1.project(PersistentHashIndexedBinaryRelation.java:488)
        at org.rascalmpl.interpreter.result.RelationResult.fieldSelect(RelationResult.java:371)
        at org.rascalmpl.interpreter.result.MapResult.fieldSelect(MapResult.java:286)
        at org.rascalmpl.interpreter.result.MapResult.fieldSelect(MapResult.java:318)
        at org.rascalmpl.semantics.dynamic.Expression$FieldProject.interpret(Expression.java:908)
        at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:365)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:882)
        at org.rascalmpl.semantics.dynamic.Command$Statement.interpret(Command.java:125)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:1090)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:959)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:914)
        at org.rascalmpl.repl.RascalInterpreterREPL.evalStatement(RascalInterpreterREPL.java:115)
        at org.rascalmpl.repl.BaseRascalREPL.handleInput(BaseRascalREPL.java:99)
        at org.rascalmpl.repl.BaseREPL.run(BaseREPL.java:283)
        at org.rascalmpl.shell.REPLRunner.run(REPLRunner.java:45)
        at org.rascalmpl.shell.RascalShell.main(RascalShell.java:126)
```

**Comment by msteindorfer** [comment]
I'll have a look at it. It didn't occur to me that indices could be used
multiple times. The actual implementation checks only all projections with
max size 2 (and dispatches on the sequence of indices).

On 18 Jul 2017, at 22:21, Paul Klint <notifications@github.com> wrote:

rascal>("a" : 1, "b" : 2, "c" : 3)<1,0,1>;
java.lang.IllegalStateException: Binary relation patterns
exhausted.(internal error)    at $shell$(|main://$shell$|)
java.lang.IllegalStateException: Binary relation patterns exhausted.
        at io.usethesource.vallang.impl.persistent.PersistentHashIndexedBinaryRelation$1.project(PersistentHashIndexedBinaryRelation.java:587)
        at io.usethesource.vallang.impl.persistent.PersistentHashIndexedBinaryRelation$1.project(PersistentHashIndexedBinaryRelation.java:488)
        at org.rascalmpl.interpreter.result.RelationResult.fieldSelect(RelationResult.java:371)
        at org.rascalmpl.interpreter.result.MapResult.fieldSelect(MapResult.java:286)
        at org.rascalmpl.interpreter.result.MapResult.fieldSelect(MapResult.java:318)
        at org.rascalmpl.semantics.dynamic.Expression$FieldProject.interpret(Expression.java:908)
        at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:365)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:882)
        at org.rascalmpl.semantics.dynamic.Command$Statement.interpret(Command.java:125)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:1090)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:959)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:914)
        at org.rascalmpl.repl.RascalInterpreterREPL.evalStatement(RascalInterpreterREPL.java:115)
        at org.rascalmpl.repl.BaseRascalREPL.handleInput(BaseRascalREPL.java:99)
        at org.rascalmpl.repl.BaseREPL.run(BaseREPL.java:283)
        at org.rascalmpl.shell.REPLRunner.run(REPLRunner.java:45)
        at org.rascalmpl.shell.RascalShell.main(RascalShell.java:126)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/usethesource/vallang/issues/4>, or mute the thread

**Comment by jurgenvinju** [comment]
this one was fixed.
