### ISSUE TITLE
failed random serialization test with only a stack trace

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/vallang#40]
```
[ERROR] testSerializable{IValueFactory, IConstructor}[96]  Time elapsed: 0.391 s  <<< ERROR!
java.io.IOException: Constructor was missing type
	at io.usethesource.vallang.io.binary.message.IValueReader.readConstructor(IValueReader.java:708)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:452)
	at io.usethesource.vallang.io.binary.message.IValueReader.readTuple(IValueReader.java:505)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:463)
	at io.usethesource.vallang.io.binary.message.IValueReader.readConstructor(IValueReader.java:683)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:452)
	at io.usethesource.vallang.io.binary.message.IValueReader.readTuple(IValueReader.java:505)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:463)
	at io.usethesource.vallang.io.binary.message.IValueReader.readConstructor(IValueReader.java:683)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:452)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:72)
	at io.usethesource.vallang.io.binary.stream.IValueInputStream.read(IValueInputStream.java:90)
	at io.usethesource.vallang.io.binary.SerializableValue.readObject(SerializableValue.java:108)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1158)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
	at io.usethesource.vallang.io.binary.SerializableValue.read(SerializableValue.java:58)
	at io.usethesource.vallang.basic.IoSmokeTest.testSerializable(IoSmokeTest.java:48)

```

but notice the weird character in this error message from the AppVeyor log:

```
IoSmokeTest.testSerializable:48 � IO Constructor was missing type
```

**Comment by jurgenvinju** [comment]
another instance:

```
<()>
<>
[ERROR] Tests run: 204, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.473 s <<< FAILURE! - in io.usethesource.vallang.basic.IoSmokeTest
[ERROR] testSerializable{IValueFactory, IConstructor}[55]  Time elapsed: 0.015 s  <<< ERROR!
java.io.IOException: Constructor was missing type
	at io.usethesource.vallang.io.binary.message.IValueReader.readConstructor(IValueReader.java:695)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:452)
	at io.usethesource.vallang.io.binary.message.IValueReader.readTuple(IValueReader.java:504)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:463)
	at io.usethesource.vallang.io.binary.message.IValueReader.readConstructor(IValueReader.java:673)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:452)
	at io.usethesource.vallang.io.binary.message.IValueReader.readTuple(IValueReader.java:505)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:463)
	at io.usethesource.vallang.io.binary.message.IValueReader.readConstructor(IValueReader.java:673)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:452)
	at io.usethesource.vallang.io.binary.message.IValueReader.readTuple(IValueReader.java:505)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:463)
	at io.usethesource.vallang.io.binary.message.IValueReader.readConstructor(IValueReader.java:673)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:452)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:72)
	at io.usethesource.vallang.io.binary.stream.IValueInputStream.read(IValueInputStream.java:67)
```

**Comment by jurgenvinju** [comment]
I have an example input which triggers the bug:

```
twotups(<true(),twotups(<not(true()),and(false(),true())>,<twotups(<couples([]),true()>,<or([]),friends([])>),twotups(<or([]),or([])>,<or([]),true()>)>)>,<twotups(<not(false()),and(true(),true())>,<twotups(<couples([]),couples([])>,<true(),couples([])>),not(false())>),and(or([true()]),twotups(<or([]),true()>,<or([]),false()>))>)
```

**Comment by jurgenvinju** [comment]
* If we change only a small sub-term, say any true() into a false(), the bug is not triggered anymore.
* Some minor changes lead to a different assertion error, in BinaryWiredInputStream.message the reader is expected a START, but its not there.

**Comment by jurgenvinju** [comment]
* important data-point: only fails with the REFERENCE factory, not with the PERSISTENT factory

**Comment by DavyLandman** [comment]
Interesting, I did change the implementation of the  reader a bit to remove all those nulls, I might have made an error there. The same value goes correctly on the previous version?

**Comment by jurgenvinju** [comment]
it's broken on the master as well; but that's already with CF. Let's see what it does before that..

**Comment by jurgenvinju** [comment]
It still fails on v0.10.0, but a little later because the code has fewer asserts:

```
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at io.usethesource.vallang.impl.reference.ValueFactory.checkNull(ValueFactory.java:48)
	at io.usethesource.vallang.impl.reference.ValueFactory.constructor(ValueFactory.java:134)
	at io.usethesource.vallang.io.binary.message.IValueReader.readConstructor(IValueReader.java:713)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:447)
	at io.usethesource.vallang.io.binary.message.IValueReader.readTuple(IValueReader.java:502)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:458)
	at io.usethesource.vallang.io.binary.message.IValueReader.readConstructor(IValueReader.java:681)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:447)
	at io.usethesource.vallang.io.binary.message.IValueReader.readConstructor(IValueReader.java:681)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:447)
	at io.usethesource.vallang.io.binary.message.IValueReader.readTuple(IValueReader.java:502)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:458)
	at io.usethesource.vallang.io.binary.message.IValueReader.readConstructor(IValueReader.java:681)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:447)
	at io.usethesource.vallang.io.binary.message.IValueReader.readValue(IValueReader.java:68)
	at io.usethesource.vallang.io.binary.stream.IValueInputStream.read(IValueInputStream.java:88)
```

**Comment by jurgenvinju** [comment]
If I change the name of the ADT "Boolean" to "B", the bug dissappears.

**Comment by jurgenvinju** [comment]
* If I change "Boolean" to "Coolea" I get "unexpected new message 5" instead of the old exception.

**Comment by jurgenvinju** [comment]
* If I change "Boolean" to "Bool" I get "Missing HOW_LOG_AGO field in PreviousType

**Comment by DavyLandman** [comment]
Okay, I have some nice examples for debug through, thanks for the research

**Comment by jurgenvinju** [comment]
Pretty sure it's not a bug in the reader or writer but rather a bug in the reference factory; constructor, tuple or list, since the bug only happens with that factory.

**Comment by jurgenvinju** [comment]
Also the binary files differ a lot, so it's probably not the reader which has a bug; everything points to the values which go into the writer. The difference must be something invisible in textual notation, but visible in binary: either types or hashCodes

**Comment by DavyLandman** [comment]
how about the visitor? as that's what is used in the writer?

**Comment by DavyLandman** [comment]
but the missing field stuff leads me to believe that there is something wrong with the writer.

**Comment by jurgenvinju** [comment]
Could be this weird leftover from earlier times: https://github.com/usethesource/vallang/blob/a8a1d1d739efc52953a29984163aa61f6cf88a44/src/main/java/io/usethesource/vallang/visitors/IValueVisitor.java#L37

I'll have a look later.

**Comment by DavyLandman** [comment]
what happens when we read in an old file that has a list relation in there?

**Comment by jurgenvinju** [comment]
List relations don't exist, set relations don't either. They are lists and sets respectively. The visitor is reminiscent of times when vallang had IRelation and IListRelation as subtypes of ISet and IList. So it should go correctly automatically, I would expect. The list relation is parsed as a list of tuples.

**Comment by DavyLandman** [comment]
so this method was never called?

**Comment by jurgenvinju** [comment]
I don't know. I guess that Either they are never called or all implementations simulate visitList

**Comment by jurgenvinju** [comment]
fixed.
